import "./globals.css";
import CustomCursor from "@/components/cursor";
export const metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  );
}
